# Generated by Django 4.2.5 on 2023-09-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApi', '0002_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ticket',
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='BookingApi.tickets'),
        ),
    ]
